name: "Pylint action"
description: "Runs pylint and sends errors in a PR message"
author: Gabriel Gazola Milan
inputs:
  GITHUB_TOKEN:
    description: "GitHub token"
    required: true
  path:
    description: "Path of files"
    required: true
  fail:
    description: "If true, the action will fail if pylint finds errors (default is true)"
    required: true
    default: true
  pr-message:
    description: "If true, the action will send a PR message if pylint finds errors (default is true)"
    required: true
    default: true
  pylint-options:
    description: "Options to be passed to pylint"
    required: false
    default: ""
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "check"
  color: "green"
